# This file is machine-generated - editing it directly is not advised

julia_version = "1.11.0-alpha1"
manifest_format = "2.0"
project_hash = "bdf11cf060274de285889af42e0933b90e74d4e0"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"
version = "1.11.0"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
version = "1.11.0"
