precompile(minimum, (Benchmark,))
precompile(process_args, (Any,))
precompile(create_function, (Symbol,))
precompile(benchmark, (Any,Any,Tuple{Any},Any))
precompile(Base.show, (IO, MIME"text/plain", Sample))
