# precompile(minimum, (Benchmark,))
# precompile(process_args, (Any,))
# precompile(create_function, (Symbol,))
# precompile(benchmark, (Any,Any,Any,Any))
# precompile(Base.show, (IO, MIME"text/plain", Sample))
