precompile(summarize, (Benchmark,))
precompile(process_args, (Any,))
precompile(create_function, (Symbol,))
precompile(create_first_function, (Symbol,))
precompile(create_function, (Expr,))
precompile(create_first_function, (Expr,))
precompile(_benchmark_1, (Any,Any,Any,Int,Int,Float64,Bool,Any))
precompile(Base.show, (IO, MIME"text/plain", Sample))
