name: Spell Check with Typos Crate
on: [pull_request]

jobs:
  run:
    name: Spell Check with Typos Crate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4

    - name: Check spelling
      uses: crate-ci/typos@master
